package com.dualbot.weatherhistory.ui.storageFragment

import com.dualbot.weatherhistory.R

class DrawableMapper {

    companion object{
        fun map(id: String?): Int {
            return when(id) {
                "c4" -> R.drawable.c4
                "c4_r1" -> R.drawable.c4_r1
                "c4_r1_st" -> R.drawable.c4_r1_st
                "c4_r2" -> R.drawable.c4_r2
                "c4_r2_st" -> R.drawable.c4_r2_st
                "c4_r3" -> R.drawable.c4_r3
                "c4_r3_st" -> R.drawable.c4_r3_st
                "c4_rs1" -> R.drawable.c4_rs1
                "c4_rs1_st" -> R.drawable.c4_rs1_st
                "c4_rs2" -> R.drawable.c4_rs2
                "c4_rs2_st" -> R.drawable.c4_rs2_st
                "c4_rs3" -> R.drawable.c4_rs3
                "c4_rs3_st" -> R.drawable.c4_rs3_st
                "c4_s1" -> R.drawable.c4_s1
                "c4_s1_st" -> R.drawable.c4_s1_st
                "c4_s2" -> R.drawable.c4_s2
                "c4_s2_st" -> R.drawable.c4_s2_st
                "c4_s3" -> R.drawable.c4_s3
                "c4_s3_st" -> R.drawable.c4_s3_st
                "c4_st" -> R.drawable.c4_st
                "d" -> R.drawable.d
                "d_c2" -> R.drawable.d_c2
                "d_c2_r1" -> R.drawable.d_c2_r1
                "d_c2_r1_st" -> R.drawable.d_c2_r1_st
                "d_c2_r2" -> R.drawable.d_c2_r2
                "d_c2_r2_st" -> R.drawable.d_c2_r2_st
                "d_c2_r3" -> R.drawable.d_c2_r3
                "d_c2_r3_st" -> R.drawable.d_c2_r3_st
                "d_c2_rs1" -> R.drawable.d_c2_rs1
                "d_c2_rs1_st" -> R.drawable.d_c2_rs1_st
                "d_c2_rs2" -> R.drawable.d_c2_rs2
                "d_c2_rs2_st" -> R.drawable.d_c2_rs2_st
                "d_c2_rs3" -> R.drawable.d_c2_rs3
                "d_c2_rs3_st" -> R.drawable.d_c2_rs3_st
                "d_c2_s1" -> R.drawable.d_c2_s1
                "d_c2_s1_st" -> R.drawable.d_c2_s1_st
                "d_c2_s2" -> R.drawable.d_c2_s2
                "d_c2_s2_st" -> R.drawable.d_c2_s2_st
                "d_c2_s3" -> R.drawable.d_c2_s3
                "d_c2_s3_st" -> R.drawable.d_c2_s3_st
                "d_c2_st" -> R.drawable.d_c2_st
                "d_c3" -> R.drawable.d_c3
                "d_c3_r1" -> R.drawable.d_c3_r1
                "d_c3_r1_st" -> R.drawable.d_c3_r1_st
                "d_c3_r2" -> R.drawable.d_c3_r2
                "d_c3_r2_st" -> R.drawable.d_c3_r2_st
                "d_c3_r3" -> R.drawable.d_c3_r3
                "d_c3_r3_st" -> R.drawable.d_c3_r3_st
                "d_c3_rs1" -> R.drawable.d_c3_rs1
                "d_c3_rs1_st" -> R.drawable.d_c3_rs1_st
                "d_c3_rs2" -> R.drawable.d_c3_rs2
                "d_c3_rs2_st" -> R.drawable.d_c3_rs2_st
                "d_c3_rs3" -> R.drawable.d_c3_rs3
                "d_c3_rs3_st" -> R.drawable.d_c3_rs3_st
                "d_c3_s1" -> R.drawable.d_c3_s1
                "d_c3_s1_st" -> R.drawable.d_c3_s1_st
                "d_c3_s2" -> R.drawable.d_c3_s2
                "d_c3_s2_st" -> R.drawable.d_c3_s2_st
                "d_c3_s3" -> R.drawable.d_c3_s3
                "d_c3_s3_st" -> R.drawable.d_c3_s3_st
                "d_c3_st" -> R.drawable.d_c3_st
                "d_st" -> R.drawable.d_st
                "moon_0" -> R.drawable.moon_0
                "moon_1" -> R.drawable.moon_1
                "moon_10" -> R.drawable.moon_10
                "moon_11" -> R.drawable.moon_11
                "moon_12" -> R.drawable.moon_12
                "moon_13" -> R.drawable.moon_13
                "moon_14" -> R.drawable.moon_14
                "moon_15" -> R.drawable.moon_15
                "moon_2" -> R.drawable.moon_2
                "moon_3" -> R.drawable.moon_3
                "moon_4" -> R.drawable.moon_4
                "moon_5" -> R.drawable.moon_5
                "moon_6" -> R.drawable.moon_6
                "moon_7" -> R.drawable.moon_7
                "moon_8" -> R.drawable.moon_8
                "moon_9" -> R.drawable.moon_9
                "n" -> R.drawable.n
                "n_c2" -> R.drawable.n_c2
                "n_c2_r1" -> R.drawable.n_c2_r1
                "n_c2_r1_st" -> R.drawable.n_c2_r1_st
                "n_c2_r2" -> R.drawable.n_c2_r2
                "n_c2_r2_st" -> R.drawable.n_c2_r2_st
                "n_c2_r3" -> R.drawable.n_c2_r3
                "n_c2_r3_st" -> R.drawable.n_c2_r3_st
                "n_c2_rs1" -> R.drawable.n_c2_rs1
                "n_c2_rs1_st" -> R.drawable.n_c2_rs1_st
                "n_c2_rs2" -> R.drawable.n_c2_rs2
                "n_c2_rs2_st" -> R.drawable.n_c2_rs2_st
                "n_c2_rs3" -> R.drawable.n_c2_rs3
                "n_c2_rs3_st" -> R.drawable.n_c2_rs3_st
                "n_c2_s1" -> R.drawable.n_c2_s1
                "n_c2_s1_st" -> R.drawable.n_c2_s1_st
                "n_c2_s2" -> R.drawable.n_c2_s2
                "n_c2_s2_st" -> R.drawable.n_c2_s2_st
                "n_c2_s3" -> R.drawable.n_c2_s3
                "n_c2_s3_st" -> R.drawable.n_c2_s3_st
                "n_c2_st" -> R.drawable.n_c2_st
                "n_c3" -> R.drawable.n_c3
                "n_c3_r1" -> R.drawable.n_c3_r1
                "n_c3_r1_st" -> R.drawable.n_c3_r1_st
                "n_c3_r2" -> R.drawable.n_c3_r2
                "n_c3_r2_st" -> R.drawable.n_c3_r2_st
                "n_c3_r3" -> R.drawable.n_c3_r3
                "n_c3_r3_st" -> R.drawable.n_c3_r3_st
                "n_c3_rs1" -> R.drawable.n_c3_rs1
                "n_c3_rs1_st" -> R.drawable.n_c3_rs1_st
                "n_c3_rs2" -> R.drawable.n_c3_rs2
                "n_c3_rs2_st" -> R.drawable.n_c3_rs2_st
                "n_c3_rs3" -> R.drawable.n_c3_rs3
                "n_c3_rs3_st" -> R.drawable.n_c3_rs3_st
                "n_c3_s1" -> R.drawable.n_c3_s1
                "n_c3_s1_st" -> R.drawable.n_c3_s1_st
                "n_c3_s2" -> R.drawable.n_c3_s2
                "n_c3_s2_st" -> R.drawable.n_c3_s2_st
                "n_c3_s3" -> R.drawable.n_c3_s3
                "n_c3_s3_st" -> R.drawable.n_c3_s3_st
                "n_c3_st" -> R.drawable.n_c3_st
                "n_st" -> R.drawable.n_st
                "r1_mist" -> R.drawable.r1_mist
                "r1_st_mist" -> R.drawable.r1_st_mist
                "r2_mist" -> R.drawable.r2_mist
                "r2_st_mist" -> R.drawable.r2_st_mist
                "r3_mist" -> R.drawable.r3_mist
                "r3_st_mist" -> R.drawable.r3_st_mist
                "rs1_mist" -> R.drawable.rs1_mist
                "rs1_st_mist" -> R.drawable.rs1_st_mist
                "rs2_mist" -> R.drawable.rs2_mist
                "rs2_st_mist" -> R.drawable.rs2_st_mist
                "rs3_mist" -> R.drawable.rs3_mist
                "rs3_st_mist" -> R.drawable.rs3_st_mist
                "s1_mist" -> R.drawable.s1_mist
                "s1_st_mist" -> R.drawable.s1_st_mist
                "s2_mist" -> R.drawable.s2_mist
                "s2_st_mist" -> R.drawable.s2_st_mist
                "s3_mist" -> R.drawable.s3_mist
                "s3_st_mist" -> R.drawable.s3_st_mist
                "snow_s1" -> R.drawable.snow_s1
                "snow_s2" -> R.drawable.snow_s2
                "snow_s3" -> R.drawable.snow_s3
                "sun" -> R.drawable.sun
                else -> R.drawable.ic_baseline_close_24
            }
        }
    }
}